[general]
show_welcome = false

[perf]
cache_shaders = true
hard_fpu = true

[display.window]
vsync = false

[sys.files]
bootrom_path = "/opt/xbox/bios/mcpx_1.0.bin"
flashrom_path = "/opt/xbox/bios/Complex_4627.bin"
eeprom_path = "/opt/xbox/eeprom.bin"
hdd_path = "/opt/xbox/xbox_hdd.qcow2"
